### ISSUE TITLE
输出维度错误

### ISSUE THREAD

**Issue by Wenpeng-huang** [eryihaha/SPACES-Pytorch#6]
作者你好，我在跑seq2seq_modle的时候，出现了维度错误，输出是[826,21128]，不应该是[826,768]吗？

![image](https://user-images.githubusercontent.com/59835263/140007433-6fefa237-310a-4904-9fb6-be53801d47a0.png)
![image](https://user-images.githubusercontent.com/59835263/140007446-aca5cbe8-1434-43f9-9dd9-87f6ab5f6597.png)

**Comment by Jeryi-Sun** [comment]
？

**Comment by Wenpeng-huang** [comment]
> _No description provided._



> _没有提供说明。_

**Comment by Wenpeng-huang** [comment]
> ？

刚刚的是nazha模型我解决了，找了一个pytorch的nazha模型。现在遇到了这个新问题。
